version: "3"

services:
  database:
    image: gukjang/mysql-reuse:1.0.0
    container_name: mysql-reuse
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: jdbc:mysql://localhost:3306/jobcat?useSSL=false
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "1234"
    ports:
      - 3306:3306
    networks:
      - network-reuse
    restart: always

  spring:
    build: .
    expose:
      - 8080
    depends_on:
      - database

networks:
  network-reuse:
    driver: bridge