name: deploy -test - chan - GukJang

on:
  push:
    branches: [ release ] # chanStar branch로 push 될 때 실행됩니다. //////

env:
  AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

#      - name: create secret files
#        working-directory: src/main/resources
#        run: |
#          touch application-prod.properties
#          echo "${{ secrets.APPLICATION_YML }}" >> application-prod.properties

      - name:  Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Project With Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean bootJar

      - name: Make zip file
        run: zip -r ./job-cat.zip ./build/libs/*.jar ./scripts/* -j ./appspec.yml
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./job-cat.zip s3://$AWS_S3_BUCKET/job-cat.zip

      - name: Code Deploy
        run: aws deploy create-deployment
          --application-name job-cat
          --deployment-config-name CodeDeployDefault.OneAtATime
          --deployment-group-name job-cat-deploy-group
          --s3-location bucket=$AWS_S3_BUCKET,bundleType=zip,key=job-cat.zip